const canvas = document.querySelector('#drawing-canvas');
const ctx = canvas.getContext('2d');
const hint = document.querySelector('#canvas-hint');
const status = document.querySelector('#save-status');
const state = { tool: 'pen', color: '#25231f', size: 5, drawing: false, last: null, history: [], redo: [], dirty: false, elapsed: 0, timer: null };
const exercises = {
  lines: { title:'Line confidence', description:'Draw long, smooth strokes from one dot to the next. Commit to every mark.', tip:'Ghost the stroke a few times before the pencil touches down.', art:'<g fill="#d86d4c">${[20,50,80,110].map(y=>`<circle cx="25" cy="${y}" r="3"/><circle cx="195" cy="${y}" r="3"/>`).join('')}</g><g stroke="#25231f" stroke-width="2" stroke-linecap="round">${[20,50,80,110].map(y=>`<path d="M 32 ${y} L 188 ${y}"/>`).join('')}</g>' },
  ellipses: { title:'Ellipses', description:'Keep your shoulder moving. Draw through the shape two or three times.', tip:'Aim for a smooth rhythm, not a perfectly precise outline.', art:'<g fill="none" stroke="#25231f" stroke-width="2"><ellipse cx="58" cy="45" rx="32" ry="16"/><ellipse cx="147" cy="45" rx="43" ry="21"/><ellipse cx="106" cy="100" rx="55" ry="25"/></g>' },
  boxes: { title:'Simple boxes', description:'Build a box from confident, parallel lines. Keep the far edges lighter.', tip:'Start by imagining where every set of parallel lines is heading.', art:'<g fill="none" stroke="#25231f" stroke-width="2" stroke-linejoin="round"><path d="M55 45 L130 32 L172 58 L96 74 Z M55 45 L55 99 L96 122 L96 74 M96 122 L172 103 L172 58"/></g>' },
  shading: { title:'Shading', description:'Fill each bar with an even value. Let pressure build gradually from light to dark.', tip:'Use the side of the Pencil and overlap strokes slightly.', art:'<g>${[0,1,2,3,4].map(i=>`<rect x="${20+i*37}" y="35" width="29" height="75" rx="3" fill="#25231f" opacity="${.12+i*.2}"/>`).join('')}</g>' }
};
function resizeCanvas() { const old = canvas.toDataURL(); const rect = canvas.getBoundingClientRect(); const ratio = Math.min(window.devicePixelRatio || 1, 2); canvas.width = Math.round(rect.width * ratio); canvas.height = Math.round(rect.height * ratio); ctx.setTransform(ratio,0,0,ratio,0,0); ctx.lineCap='round'; ctx.lineJoin='round'; if (state.history.length) { const img = new Image(); img.onload=()=>ctx.drawImage(img,0,0,rect.width,rect.height); img.src=old; } }
function snapshot() { return canvas.toDataURL('image/png'); }
function restore(data) { const img=new Image(); img.onload=()=>{ ctx.clearRect(0,0,canvas.width,canvas.height); ctx.drawImage(img,0,0,canvas.clientWidth,canvas.clientHeight); }; img.src=data; }
function updateHistory() { document.querySelector('#undo').disabled=state.history.length<2; document.querySelector('#redo').disabled=!state.redo.length; }
function saveState() { state.history.push(snapshot()); if(state.history.length>25) state.history.shift(); state.redo=[]; updateHistory(); }
function point(e) { const r=canvas.getBoundingClientRect(); return {x:e.clientX-r.left,y:e.clientY-r.top, pressure:e.pressure || .5}; }
function draw(e) { if(!state.drawing) return; e.preventDefault(); const p=point(e), previous=state.last; const pressure = e.pointerType==='pen' ? Math.max(.2,p.pressure) : 1; ctx.globalCompositeOperation=state.tool==='eraser'?'destination-out':'source-over'; ctx.strokeStyle=state.color; ctx.lineWidth=state.size*(state.tool==='eraser'?2.5:pressure); ctx.beginPath(); ctx.moveTo(previous.x,previous.y); ctx.lineTo(p.x,p.y); ctx.stroke(); state.last=p; state.dirty=true; hint.style.opacity=0; }
canvas.addEventListener('pointerdown', e=>{ if(e.pointerType==='mouse' && e.button!==0) return; canvas.setPointerCapture(e.pointerId); state.drawing=true; state.last=point(e); if(!state.history.length) saveState(); draw(e); });
canvas.addEventListener('pointermove', draw);
['pointerup','pointercancel','pointerleave'].forEach(type=>canvas.addEventListener(type,e=>{ if(state.drawing){ state.drawing=false; if(state.dirty){ saveState(); localStorage.setItem('draw-daily-draft',snapshot()); status.textContent='Saved automatically'; } } }));
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{ state.tool=b.dataset.tool; document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b)); }));
document.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{ state.color=b.dataset.color; state.tool='pen'; document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('active',x===b)); document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x.dataset.tool==='pen')); }));
document.querySelector('#brush-size').addEventListener('input',e=>{state.size=+e.target.value;document.querySelector('#brush-output').value=state.size;});
document.querySelector('#undo').addEventListener('click',()=>{ if(state.history.length<2)return; state.redo.push(state.history.pop()); restore(state.history.at(-1)); updateHistory(); });
document.querySelector('#redo').addEventListener('click',()=>{const next=state.redo.pop();if(next){state.history.push(next);restore(next);updateHistory();}});
document.querySelector('#clear').addEventListener('click',()=>{if(confirm('Clear this canvas? Your saved gallery drawings will remain.')){ctx.clearRect(0,0,canvas.width,canvas.height);saveState();hint.style.opacity=1;}});
function setExercise(key) { const e=exercises[key]; document.querySelector('#exercise-title').textContent=e.title; document.querySelector('#exercise-description').textContent=e.description; document.querySelector('#exercise-tip').textContent=e.tip; document.querySelector('#reference-art').innerHTML=e.art; localStorage.setItem('draw-daily-exercise',key); }
document.querySelector('#exercise-select').addEventListener('change',e=>setExercise(e.target.value));
function getGallery(){return JSON.parse(localStorage.getItem('draw-daily-gallery')||'[]');} function renderGallery(){const grid=document.querySelector('#gallery-grid'),items=getGallery();document.querySelector('#gallery-count').textContent=items.length?`(${items.length})`:'';grid.innerHTML=items.length?items.map(i=>`<article class="gallery-card"><img src="${i.image}" alt="Saved ${i.exercise} drawing"><div><strong>${i.exercise}</strong><span>${i.date}</span></div></article>`).join(''):'<div class="empty-gallery">Your saved drawings will appear here.<br>Practice a small drill, then save it.</div>';}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}
document.querySelector('#save-drawing').addEventListener('click',()=>{const gallery=getGallery();gallery.unshift({image:snapshot(),exercise:document.querySelector('#exercise-title').textContent,date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})});localStorage.setItem('draw-daily-gallery',JSON.stringify(gallery.slice(0,30)));renderGallery();toast('Drawing saved to your gallery');});
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>{const gallery=b.dataset.view==='gallery';document.querySelector('#practice-view').classList.toggle('active',!gallery);document.querySelector('#gallery-view').classList.toggle('active',gallery);document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x===b));if(gallery)renderGallery();}));
document.querySelector('#timer-button').addEventListener('click',e=>{if(state.timer){clearInterval(state.timer);state.timer=null;e.currentTarget.textContent='▶';}else{state.timer=setInterval(()=>{state.elapsed++;const m=String(Math.floor(state.elapsed/60)).padStart(2,'0'),s=String(state.elapsed%60).padStart(2,'0');document.querySelector('#timer-display').textContent=`${m}:${s}`;},1000);e.currentTarget.textContent='Ⅱ';}});
window.addEventListener('resize',resizeCanvas); window.addEventListener('orientationchange',()=>setTimeout(resizeCanvas,150));
resizeCanvas(); const saved=localStorage.getItem('draw-daily-draft');if(saved){state.history=[saved];restore(saved);hint.style.opacity=0;updateHistory();} const initial=localStorage.getItem('draw-daily-exercise')||'lines';document.querySelector('#exercise-select').value=initial;setExercise(initial);renderGallery();
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js');
